trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform
      - pipelines/terraform.yml

pool: Default

steps:
  # We start by reading the secrets from the key vault into the environment variables.
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: sp-rup-ref-terraform
      KeyVaultName: kv-rup-ref-dev-we-01
      SecretsFilter: "*"
      RunAsPreJob: false
  # Install terraform CLI
  - task: TerraformInstaller@0
    displayName: Install Terraform CLI
    inputs:
      terraformVersion: "1.3.7"
  # Apply terraform configuration
  - task: Bash@3
    displayName: Apply Terraform Configuration
    inputs:
      targetType: "inline"
      workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"
      script: |
        set -euo pipefail
        terraform init -input=false
        terraform validate
        terraform apply -input=false -auto-approve
    env:
      ARM_CLIENT_ID: $(kvs-rup-ref-dev-terraform-sp-client-id)
      ARM_CLIENT_SECRET: $(kvs-rup-ref-dev-terraform-sp-client-secret)
      ARM_TENANT_ID: $(kvs-rup-ref-dev-terraform-sp-client-tenant-id)
      ARM_SUBSCRIPTION_ID: $(kvs-rup-ref-dev-subscription-id)
